services:
  - type: web
    name: java-portfolio
    env: java
    plan: free
    buildCommand: npm install && npm run build:tailwind && ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/portfolio-app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: MAVEN_OPTS
        value: "-Xmx512m"
      - key: NODE_VERSION
        value: 18